### PR TITLE
fix filesFinder permission error

### LINKED ISSUE #39: no access to some files in fileFinder
in case of path that contains files that we don't have access to them there is no error

### PR DESCRIPTION
**Pull request by michal367**
closes #39

### CODE REVIEW

File: server/src/modules/mainModule/filesFinder.ts [hunk 1]
```diff
@@ -3,17 +3,23 @@ import path from 'path';
...
 
 export function* directoryFilesGenerator(baseFolder: string, recursive: boolean = true): IterableIterator<string> {
-    const currDirFiles: string[] = fs.readdirSync(baseFolder);
-    const absoluteFiles: string[] = currDirFiles.map((file: string) => path.join(baseFolder, file))
+    let currDirFiles: string[] = [];
+    try{
+        currDirFiles = fs.readdirSync(baseFolder);
+    }
+    catch{
+        return;
```
Comment (Derstilon) [inline server/src/modules/mainModule/filesFinder.ts:11]: Are you sure this won't break the generator function?
If you return from generator it counts as .done?

Comment (michal367) [reply server/src/modules/mainModule/filesFinder.ts:11]: return will end recursive function execution, but not generator

**Review by Derstilon — APPROVED** [review]
image
The generator looks great now!
